import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { images } from "@/constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "New App",
  description: "Generated by create next app",
  openGraph: {
    title: "New App",
    description: "Generated by create next app",
    images: [
      {
        // url: images[Math.floor(Math.random() * images.length)],
        url: "https://images.pexels.com/photos/27643389/pexels-photo-27643389/free-photo-of-santo-amaro-lencois-maranhenses.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630",
        width: 1200,
        height: 630,
        alt: "Description of the image",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary", // Specify the card type
    title: "New App",
    description: "Generated by create next",
    images: [
      {
        url: "https://plus.unsplash.com/premium_photo-1734626880757-a107821e718e?w=1200&h=630&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwyfHx8ZW58MHx8fHx8",
        alt: "Description of the image",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
